# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./cmd/ ./cmd
COPY ./internal/ ./internal
COPY ./proto/ ./proto

RUN go build -o /waterloo ./cmd/app.go

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /waterloo /waterloo

EXPOSE 9155:9155

USER nonroot:nonroot

CMD ["/waterloo"]
