// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: waterloo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // Youtube Video ID
}

func (x *CacheSearch) Reset() {
	*x = CacheSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waterloo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSearch) ProtoMessage() {}

func (x *CacheSearch) ProtoReflect() protoreflect.Message {
	mi := &file_waterloo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSearch.ProtoReflect.Descriptor instead.
func (*CacheSearch) Descriptor() ([]byte, []int) {
	return file_waterloo_proto_rawDescGZIP(), []int{0}
}

func (x *CacheSearch) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type CacheResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // TrackID UUID
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                       // Video title
	Channel       string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`                                   // Channel name
	RegionBlocked bool   `protobuf:"varint,4,opt,name=region_blocked,json=regionBlocked,proto3" json:"region_blocked,omitempty"` // Is region blocked for specified region
	EmbedBlocked  bool   `protobuf:"varint,5,opt,name=embed_blocked,json=embedBlocked,proto3" json:"embed_blocked,omitempty"`    // Is blocked for embedded players
	Duration      int64  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`                                // Duration in seconds
	Found         bool   `protobuf:"varint,7,opt,name=found,proto3" json:"found,omitempty"`                                      // Found in cache
}

func (x *CacheResult) Reset() {
	*x = CacheResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waterloo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResult) ProtoMessage() {}

func (x *CacheResult) ProtoReflect() protoreflect.Message {
	mi := &file_waterloo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResult.ProtoReflect.Descriptor instead.
func (*CacheResult) Descriptor() ([]byte, []int) {
	return file_waterloo_proto_rawDescGZIP(), []int{1}
}

func (x *CacheResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CacheResult) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CacheResult) GetRegionBlocked() bool {
	if x != nil {
		return x.RegionBlocked
	}
	return false
}

func (x *CacheResult) GetEmbedBlocked() bool {
	if x != nil {
		return x.EmbedBlocked
	}
	return false
}

func (x *CacheResult) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CacheResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type CacheVideoDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // TrackID UUID
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                       // Video title
	Channel       string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`                                   // Channel name
	RegionBlocked bool   `protobuf:"varint,4,opt,name=region_blocked,json=regionBlocked,proto3" json:"region_blocked,omitempty"` // Is region blocked for specified region
	EmbedBlocked  bool   `protobuf:"varint,5,opt,name=embed_blocked,json=embedBlocked,proto3" json:"embed_blocked,omitempty"`    // Is blocked for embedded players
	Duration      int64  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`                                // Duration in seconds
}

func (x *CacheVideoDetails) Reset() {
	*x = CacheVideoDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waterloo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheVideoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVideoDetails) ProtoMessage() {}

func (x *CacheVideoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_waterloo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVideoDetails.ProtoReflect.Descriptor instead.
func (*CacheVideoDetails) Descriptor() ([]byte, []int) {
	return file_waterloo_proto_rawDescGZIP(), []int{2}
}

func (x *CacheVideoDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheVideoDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CacheVideoDetails) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CacheVideoDetails) GetRegionBlocked() bool {
	if x != nil {
		return x.RegionBlocked
	}
	return false
}

func (x *CacheVideoDetails) GetEmbedBlocked() bool {
	if x != nil {
		return x.EmbedBlocked
	}
	return false
}

func (x *CacheVideoDetails) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type StoreStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State bool  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"` // Status of storage
	Ttl   int64 `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`     // Duration of key in redis
}

func (x *StoreStatus) Reset() {
	*x = StoreStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waterloo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStatus) ProtoMessage() {}

func (x *StoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_waterloo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStatus.ProtoReflect.Descriptor instead.
func (*StoreStatus) Descriptor() ([]byte, []int) {
	return file_waterloo_proto_rawDescGZIP(), []int{3}
}

func (x *StoreStatus) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *StoreStatus) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_waterloo_proto protoreflect.FileDescriptor

var file_waterloo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6f, 0x6e, 0x65, 0x74, 0x68, 0x69, 0x72, 0x74, 0x79, 0x6f, 0x6e, 0x65, 0x22, 0x28,
	0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x19, 0x0a,
	0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x0e,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65, 0x6d, 0x62, 0x65,
	0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x32, 0x9e, 0x01, 0x0a, 0x17,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x51, 0x75, 0x65, 0x75, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x12, 0x19, 0x2e, 0x6f, 0x6e, 0x65, 0x74, 0x68, 0x69, 0x72, 0x74, 0x79, 0x6f, 0x6e, 0x65,
	0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x19, 0x2e, 0x6f,
	0x6e, 0x65, 0x74, 0x68, 0x69, 0x72, 0x74, 0x79, 0x6f, 0x6e, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x43, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x12, 0x1f, 0x2e, 0x6f, 0x6e, 0x65, 0x74, 0x68, 0x69, 0x72, 0x74, 0x79, 0x6f, 0x6e, 0x65, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x1a, 0x19, 0x2e, 0x6f, 0x6e, 0x65, 0x74, 0x68, 0x69, 0x72, 0x74, 0x79, 0x6f, 0x6e, 0x65,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x22, 0x5a, 0x20,
	0x70, 0x65, 0x70, 0x65, 0x67, 0x61, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x6f, 0x6e, 0x65, 0x74, 0x68,
	0x69, 0x72, 0x74, 0x79, 0x6f, 0x6e, 0x65, 0x2f, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x6f, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_waterloo_proto_rawDescOnce sync.Once
	file_waterloo_proto_rawDescData = file_waterloo_proto_rawDesc
)

func file_waterloo_proto_rawDescGZIP() []byte {
	file_waterloo_proto_rawDescOnce.Do(func() {
		file_waterloo_proto_rawDescData = protoimpl.X.CompressGZIP(file_waterloo_proto_rawDescData)
	})
	return file_waterloo_proto_rawDescData
}

var file_waterloo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_waterloo_proto_goTypes = []interface{}{
	(*CacheSearch)(nil),       // 0: onethirtyone.CacheSearch
	(*CacheResult)(nil),       // 1: onethirtyone.CacheResult
	(*CacheVideoDetails)(nil), // 2: onethirtyone.CacheVideoDetails
	(*StoreStatus)(nil),       // 3: onethirtyone.StoreStatus
}
var file_waterloo_proto_depIdxs = []int32{
	0, // 0: onethirtyone.PublicQueueCacheService.lookup:input_type -> onethirtyone.CacheSearch
	2, // 1: onethirtyone.PublicQueueCacheService.store:input_type -> onethirtyone.CacheVideoDetails
	1, // 2: onethirtyone.PublicQueueCacheService.lookup:output_type -> onethirtyone.CacheResult
	3, // 3: onethirtyone.PublicQueueCacheService.store:output_type -> onethirtyone.StoreStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_waterloo_proto_init() }
func file_waterloo_proto_init() {
	if File_waterloo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waterloo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waterloo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waterloo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheVideoDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waterloo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waterloo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_waterloo_proto_goTypes,
		DependencyIndexes: file_waterloo_proto_depIdxs,
		MessageInfos:      file_waterloo_proto_msgTypes,
	}.Build()
	File_waterloo_proto = out.File
	file_waterloo_proto_rawDesc = nil
	file_waterloo_proto_goTypes = nil
	file_waterloo_proto_depIdxs = nil
}
